"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Empty(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
global___Empty = Empty

class ToDo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    id: typing.Text
    name: typing.Text
    status: typing.Text

    def __init__(self, *, id: typing.Text=..., name: typing.Text=..., status: typing.Text=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['id', b'id', 'name', b'name', 'status', b'status']) -> None:
        ...
global___ToDo = ToDo