"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import collections.abc
import grpc
from . import todo_pb2

class ToDoApplicationStub:

    def __init__(self, channel: grpc.Channel) -> None:
        ...
    GetAll: grpc.UnaryStreamMultiCallable[todo_pb2.Empty, todo_pb2.ToDo]
    'rpc GetById (Empty) returns (ToDo);'

class ToDoApplicationServicer(metaclass=abc.ABCMeta):

    @abc.abstractmethod
    def GetAll(self, request: todo_pb2.Empty, context: grpc.ServicerContext) -> collections.abc.Iterator[todo_pb2.ToDo]:
        """rpc GetById (Empty) returns (ToDo);"""

def add_ToDoApplicationServicer_to_server(servicer: ToDoApplicationServicer, server: grpc.Server) -> None:
    ...