name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "!**.md"

jobs:
  code-check:
    uses: koei-kaji/reusable-github-actions/.github/workflows/python-code-check.yaml@1.0.0
    with:
      python-version: 3.10.5
      pip-version: 22.2.2
      command-check-format: "make format-check"
      command-lint: "make lint"
      command-test: "make test"
