name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  code-check:
    uses: koei-kaji/reusable-github-actions/.github/workflows/python-code-check.yaml@v1.1.2
    with:
      python-version: 3.10.5
      poetry-version: 1.1.13
      command-check-format: "make format-check"
      command-lint: "make lint"
      command-test: "make test"

  docker-check-rest:
    needs: code-check
    uses: koei-kaji/reusable-github-actions/.github/workflows/docker-check.yaml@v1.1.2
    with:
      docker-filename: Dockerfile.rest
