name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      # check-out repo & set-up python
      #----------------------------------------------
      - name: Check out repository
        id: check-out-repository
        uses: actions/checkout@v3

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          cache: "pip"

      - name: Install dependencies
        id: install-dependencies
        run: pip install -r requirements-dev.lock

      #----------------------------------------------
      # run test suite
      #----------------------------------------------
      - name: Check format
        id: check-format
        run: |
          isort --check --extend-skip src/_grpc/ .
          black --check --extend-exclude src/_grpc/ .

      - name: Lint
        id: lint
        run: |
          pylint -d C,R,fixme --ignore-paths=src/_grpc/ src/
          mypy --show-error-codes --exclude src/_grpc/ src/

      - name: Test
        id: test
        run: pytest src/tests

  docker-check-rest:
    needs: code-check
    uses: koei-kaji/reusable-github-actions/.github/workflows/docker-check.yaml@v1.1.4
    with:
      dockerfile-name: Dockerfile.rest

  docker-check-grpc:
    needs: code-check
    uses: koei-kaji/reusable-github-actions/.github/workflows/docker-check.yaml@v1.1.4
    with:
      dockerfile-name: Dockerfile.grpc
