name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  code-check:
    uses: koei-kaji/reusable-github-actions/.github/workflows/python-code-check.yaml@v1.1.4
    with:
      python-version: 3.10.7
      poetry-version: 1.3.2
      command-check-format: "make format-check"
      command-lint: "make lint"
      command-test: "make test"

  docker-check-rest:
    needs: code-check
    uses: koei-kaji/reusable-github-actions/.github/workflows/docker-check.yaml@v1.1.4
    with:
      dockerfile-name: Dockerfile.rest

  docker-check-grpc:
    needs: code-check
    uses: koei-kaji/reusable-github-actions/.github/workflows/docker-check.yaml@v1.1.4
    with:
      dockerfile-name: Dockerfile.grpc
